image: docker.kbt.io/postgis/build-test:trisquel

before_script:
    - lsb_release -a
    - service postgresql start

test:
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make check RUNTESTFLAGS=-v
    - make check RUNTESTFLAGS="-v --dumprestore"
    - make install
    - make installcheck RUNTESTFLAGS=-v
    - make installcheck RUNTESTFLAGS="-v --dumprestore"
