image: docker.kbt.io/postgis/build-test:trisquel

before_script:
  - lsb-release -a

test:
  script:
    - lsb_release -a
    - uname -a
    - ./autogen.sh
    - ./configure
    - make
    - make check
    - install -m 755 /bin/true /usr/local/bin/git2cl
    - make distcheck
